In [40]:
import numpy as np


X = np.array([0.1,0.5,0.8])

weights = np.array([[0.4967,1.5230,1.5792],[-0.1383,-0.2342,0.7674],[0.6477,-0.2341,-0.4695]]).T
b = np.array([0.5425,-0.4616,-0.4657])

In [42]:
def forward(X, w, b):
    # Ensure X is a row vector
    X = X.reshape(1, -1)
    z = np.dot(X, w) + b
    a = 1 / (1 + np.exp(-z))
    print(z)
    print(a)
    return a
# Call the function
forward(X, weights, b)

[[ 2.61703  0.02139 -0.89358]]
[[0.93194959 0.5053473  0.29037159]]


array([[0.93194959, 0.5053473 , 0.29037159]])

In [48]:
X2 = np.array([0.93194959, 0.5053473 , 0.29037159])

w2 = np.array([[0.5426,0.2419,-0.5623],[-0.4634,-1.9132,-1.0128],[-0.4657,-1.7249,0.3142]]).T

b2 = np.array([0.2419,-1.9133,-1.7249])

forward(X2, w2, b2)

[[ 0.70654341 -3.60608424 -2.93934773]]
[[0.66963693 0.02643993 0.05024239]]


array([[0.66963693, 0.02643993, 0.05024239]])

In [49]:
X3 = np.array([0.66963693, 0.02643993, 0.05024239])

w3 = np.array([[-0.9080,-0.2258,-0.5444],[-1.4123,0.0675,0.1109],[1.4656,-1.4247,-1.1500]]).T

b3 = np.array([-0.5623,-1.0128,0.3142])

forward(X3, w3, b3)

[[-1.20365243 -1.95117166  1.20017217]]
[[0.23082611 0.12442566 0.76855541]]


array([[0.23082611, 0.12442566, 0.76855541]])

In [50]:
X4 = np.array([0.23082611, 0.12442566, 0.76855541])

w4 = np.array([[0.3757,-0.2917,0.1852],[-0.6006,-0.6017,-1.1063]]).T

b4 = np.array([0.3757,-0.6006])

forward(X4, w4, b4)

[[ 0.56846287 -1.66435393]]
[[0.63840841 0.1591784 ]]


array([[0.63840841, 0.1591784 ]])

In [53]:
y = 1  
loss = - (y * np.log(0.63840841) + (1 - y) * np.log(1 - 0.63840841))

print("Loss is ",loss)

Loss is  0.4487770593744113


In [64]:
y = 0
loss = - (y * np.log(0.1591784) + (1 - y) * np.log(1 - 0.1591784))

print("Loss is ",loss)

Loss is  0.17337576993015372


In [65]:
def loss(a,y):
    loss = - (y * np.log(a) + (1 - y) * np.log(1-a))
    return loss
loss(0.1591784,0)

0.17337576993015372